using System;
using System.ComponentModel.DataAnnotations;

namespace ContactManager.Models
{
    public class Contact
    {
        // primary key - generated by database
        public int ContactId { get; set; }         

        [Required(ErrorMessage = "Please enter a first name.")]
        public string Firstname { get; set; }

        [Required(ErrorMessage = "Please enter a first name.")]
        public string Lastname { get; set; }

        [Required(ErrorMessage = "Please enter a phone number.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please enter an email.")]
        public string Email { get; set; }

        public string Organization { get; set; }  // no validation bc optional
        public DateTime DateAdded { get; set; }   // no validation bc will be set by application, not user

        // foreign key
        [Range(1, 100000000, ErrorMessage = "Please select a category.")] // make sure value is greater than zero
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        // read-only property
        public string Slug => Firstname?.Replace(' ', '-').ToLower() 
            + '-' + Lastname?.Replace(' ', '-').ToLower();
    }
}
